### ISSUE TITLE
swipe between project images on mobile

### ISSUE THREAD

**Issue by bennlich** [bennlich/sds-dev#10]

**Comment by cyamane08** [comment]
![2015-10-11 19 51 17](https://cloud.githubusercontent.com/assets/6592363/10422279/f85b7f4a-706c-11e5-87ce-e8c327bb376b.jpg)
add swipe status indicator

**Comment by bennlich** [comment]
Fixed by https://github.com/bennlich/sds-dev/commit/2f1dbf5373bb736ec8ff227f8695c69aaa0f1f51 except for #13
