### ISSUE TITLE
look at about page

### ISSUE THREAD

**Issue by cyamane08** [bennlich/sds-dev#7]
picture of chris and matt goes off the screen on the right

**Comment by cyamane08** [comment]
Meeeoowwwse

**Comment by cyamane08** [comment]
Can you bring the gentleplants version up to where you are when you're done
working today? I wanna check it out

**Comment by bennlich** [comment]
Way ahead of ya :-P Check your slack.

**Comment by cyamane08** [comment]
Oh you foxy little minx
